on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

name: Continuous integration

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  ci-pass:
    name: CI succeeded
    runs-on: ubuntu-latest
    if: always()

    needs:
      - test
      - check-examples
      - fmt
      - msrv

    steps:
      - name: Check whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run tests
        run: cargo test --workspace

  check-examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: examples
          cache-on-failure: true

      - name: Check examples
        run: cargo check --manifest-path=./examples/Cargo.toml

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --all -- --check

  msrv:
    name: MSRV (1.83)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.83
        run: rustup install 1.83 --profile minimal

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check MSRV
        run: cargo +1.83 check --workspace
